# **Python Fundamentals**

## **Data Types**

In [1]:

# Basic data types
x = 10          # int
y = 3.14        # float
name = "Alice"  # string
flag = True     # boolean

print(type(x), type(y), type(name), type(flag))

<class 'int'> <class 'float'> <class 'str'> <class 'bool'>


---
## **Data Structures**

### 1. Lists

A **list** in Python is an ordered, mutable collection used to store multiple items in a single variable. Lists can contain elements of different data types (such as integers, floats, strings, or even other lists), and their contents can be modified after creation.

Lists support indexing, slicing, iteration, and a wide range of built-in operations such as adding, removing, and searching for elements. Because of their flexibility and ease of use, lists are one of the most commonly used data structures in Python.


In [1]:
lst = [1,2,3]
lst.append(4)
lst + [4]

[1, 2, 3, 4, 4]

In [2]:
lst = [1, 2, 3]            # create a list with initial elements
lst.append(4)             # add 4 to the end of the list

lst + [5]                 # concatenate list with [5]
lst2 = lst + [5]
lst * 2                   # repeat the list twice
2 in lst                  # check if 2 exists in the list
len(lst)                  # get the length of the list
lst[1]                    # access element at index 1
lst[0:3:1]                # slice the list from index 0 to 2 with step 1
del lst2[0]
lst2[::-1]
lst
# 

[1, 2, 3, 4]

In [3]:
lst.append(2)             # add another 2 to the list
lst.count(2)              # count how many times 2 appears in the list
lst.index(3)              # get index of the first occurrence of 3
del lst[0]                # delete the element at index 0
lst

[2, 3, 4, 2]

### 2. Tuples

A **tuple** is an ordered, **immutable** collection of elements in Python. Tuples are similar to lists, but once created, their values **cannot be changed**.


In [4]:
t = (1, 2, 3)        # create a tuple with initial elements
t + (4,)            # concatenate tuple with (4,)
t * 2               # repeat the tuple twice
2 in t              # check if 2 exists in the tuple
len(t)              # get the length of the tuple
t[1]                # access element at index 1
t[0:3]              # slice the tuple from index 0 to 2

(1, 2, 3)

In [5]:
t + (4,)            # concatenate tuple with (4,)
t * 2               # repeat the tuple twice
t[::2]

(1, 3)

In [6]:
a = {1, 2, 3}     # define set a
b = {3, 4, 5}     # define set b

a & b             # intersection of sets a and b
a | b             # union of sets a and b
a - b             # difference (elements in a but not in b)
a ^ b             # symmetric difference (elements in either set, but not both)

d = [11,2,2,3,3]
set(d)

{2, 3, 11}

In [7]:
a - b             # difference (elements in a but not in b)


{1, 2}

### 4. Dictionaries

A **dictionary** in Python is a built-in data type used to store data in **key–value pairs**.  
Each key maps to a value, allowing fast lookup, insertion, and deletion.

Dictionaries are:
- **Unordered** (before Python 3.7) / **Insertion-ordered** (Python 3.7+)
- **Mutable** (can be changed after creation)
- Indexed by **keys**, not by position


In [8]:
d = {"a": 1, "b": 2}    # create a dictionary with key-value pairs
d["a"]                 # access the value associated with key "a"

d.keys()               # get all keys in the dictionary
d.values()             # get all values in the dictionary
d.items()              # get all key-value pairs
"a" in d               # check if key "a" exists in the dictionary
del d["a"]             # delete the key "a" from the dictionary
# keys should be immutable types (like strings, numbers, tuples), while values can be of any type (including mutable types like lists and dictionaries)
# how many values in a list

In [9]:
d = {"a": 1, "b": 2}    # create a dictionary with key-value pairs
list(d.items())

# Set only unique values

[('a', 1), ('b', 2)]

In [10]:
d.items()              # get all key-value pairs
type(d.keys())

# list, sets, tuples, dictionaries

dict_keys

### 5. Numpy

- Provides the ndarray, a fast, efficient homogeneous array for numerical data.
- Ideal for mathematical operations, vectorized computations, and linear algebra.

Features:

- Fixed-size arrays with fast indexing and slicing
- Efficient memory usage for large datasets
- Supports broadcasting and element-wise operations

In [11]:
import numpy as np
# all entries must be of the same type
# Create arrays
arr1 = np.array([1, 2, 3, 4])             # 1D array
arr2 = np.array([[1, 2], [3, 4]])         # 2D array

# Basic arithmetic
print(arr1 + 10)                           # Add 10 to each element
print(arr1 * 2)                            # Multiply each element by 2
print(arr1 - np.array([1,1,1,1]))          # Element-wise subtraction

# Array operations
print(arr1.sum())                           # Sum of all elements
print(arr1.mean())                          # Mean of elements
print(arr1.max(), arr1.min())               # Max and Min
print(arr1.argmax())                        # Index of max element

# Indexing and slicing
print(arr1[0])                              # First element
print(arr1[1:3])                            # Slice: elements at index 1 and 2
print(arr2[:, 1])                           # Second column of 2D array

# Reshape and size
print(arr2.shape)                           # Shape of array (rows, columns)
print(arr2.reshape(4,1))                    # Reshape to 4x1 array
print(arr2.size)                            # Total number of elements


# Broadcasting
print(arr2 + np.array([10, 20]))            # Add row-wise (broadcasting)
print(arr2 * 2)                             # Multiply all elements by 2

# Logical operations
print(arr1 > 2)                             # Element-wise comparison -> boolean array
print(arr1[arr1 > 2])                        # Filter elements > 2

# Linear algebra (dot product)
arr3 = np.array([[1,2],[3,4]])
arr4 = np.array([[5,6],[7,8]])
print(np.dot(arr3, arr4))                   # Matrix multiplication

# Random numbers
rand_arr = np.random.rand(3,3)             # 3x3 array with random floats [0,1)
print(rand_arr)

[11 12 13 14]
[2 4 6 8]
[0 1 2 3]
10
2.5
4 1
3
1
[2 3]
[2 4]
(2, 2)
[[1]
 [2]
 [3]
 [4]]
4
[[11 22]
 [13 24]]
[[2 4]
 [6 8]]
[False False  True  True]
[3 4]
[[19 22]
 [43 50]]
[[0.14784834 0.26581577 0.07357005]
 [0.7562064  0.93118483 0.27148248]
 [0.20262261 0.84470913 0.90763733]]


In [12]:
arr3 = np.array([[1,2],[3,4]])
arr4 = np.array([[5,6],[7,8]])
print(np.dot(arr3, arr4))                   # Matrix multiplication



[[19 22]
 [43 50]]


In [13]:
a1 = np.array([1, 2, 3])
print(a1[a1 > 1])  # Select elements in a1 that are greater than 1
# a2 = np.array([4, 5, 6])
# print(a1 + a2)                             # Element-wise addition

# tupple as key in dictionary
# Assume we have attendence of day 1 day 2 of the students
# Aim is to find the students who attenedded both the days what should the data structur be? 
# Use set - use intersection to find common studentsss

[2 3]


## 6. Pandas

- Provides DataFrame and Series, high-level structures for heterogeneous tabular data.
- Ideal for data manipulation, cleaning, and analysis.

Features:

- Columns can have different types (numbers, strings, dates)
- Built-in methods for filtering, grouping, aggregation
- Handles missing data gracefully
- Can read/write CSV, Excel, JSON, SQL, and more

In [14]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "score": [85, 90, 78]
})

# every column must have the same data type

In [15]:
arr = np.array([[1,2],[3,4]])
arr + np.array([1,1])


array([[2, 3],
       [4, 5]])

In [16]:
import numpy as np
arr = np.array([10, 50, 30, 20])

print(arr.max())    # Output: 50
print(arr.argmax()) # Output: 1 (because 50 is at index 1)

50
1


In [17]:
#!/bin/bash
# ^ Question 17: The Shebang tells the system to use the Bash interpreter.

# Question 14: Use $0 to print the name of the script itself.
!echo "The name of this script is: $0"

# Question 15: Demonstrating the difference between literal strings and variables.
VAR="Data"
!echo "Printing 'VAR' as a string:"
!echo VAR       # Output: VAR
!echo "Printing the contents of \$VAR:"
!echo $VAR      # Output: Data

# Question 16: Numerical comparison using -ge (greater than or equal to).
x=15
if [ $x -ge 10 ]; then
    !echo "Check passed: $x is greater than or equal to 10."
else
    !echo "Check failed: $x is less than 10."
fi

SyntaxError: invalid syntax (809069174.py, line 16)