In [1]:
import numpy as np

# Create a 2D array of shape (3, 4)
# Think of this as 3 rows and 4 columns
array_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Create a 1D array of shape (4,)
# This has the same number of columns as the 2D array
array_1d = np.array([10, 20, 30, 40])

# Perform the addition
# NumPy "broadcasts" the 1D array across each row of the 2D array
result = array_2d + array_1d

print("2D Array (3, 4):")
print(array_2d)
print("\n1D Array (4,):")
print(array_1d)
print("\nResult of Addition:")
print(result)

2D Array (3, 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1D Array (4,):
[10 20 30 40]

Result of Addition:
[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


In [1]:
lst = [1,2,3]
lst.append(4)
lst[2::-1] = [5,6,7]
print(lst)

[7, 6, 5, 4]
